Add support for more than one destination
RushPlay/fortytwoish pull request #2
Opened 2018-04-12 11:37 UTC by davorb

2018-04-12 14:09 UTC, lunich requested changes

2018-04-12 14:09 UTC, lunich commented on lib/fortytwoish/client.rb
> +    end
Probably we can have `attr_reader :numbers` instead + do `@numbers = Array.wrap(numbers)` in the `initialize`?

2018-04-12 14:16 UTC, lunich commented on lib/fortytwoish/client.rb
> +    end
Thanks to @jonkerz for pointing out that `Array#wrap` is `active_support`s method.
It's implementation is simple, we can use it partially:
```ruby
def self.wrap(object)
  if object.nil?
    []
  elsif object.respond_to?(:to_ary)
    object.to_ary
  else
    [object]
  end
end
```

2018-04-12 14:16 UTC, jonkerz commented on lib/fortytwoish/client.rb
> +    end
http://route.github.io/2012/08/28/see-the-difference.html

2018-04-12 14:16 UTC, lunich commented on lib/fortytwoish/client.rb
> +    end
But still let's move to `initializer`?

2018-04-12 14:17 UTC, davorb commented on lib/fortytwoish/client.rb
> +    end
No, we can't do that. `Array.wrap` is only available in Rails.

2018-04-12 14:18 UTC, davorb commented on lib/fortytwoish/client.rb
> +    end
Done in babc851 (commit sha sounds like my last name)

2018-04-12 14:22 UTC, jonkerz approved these changes

2018-04-16 07:09 UTC, lunich approved these changes

2018-04-16 07:25 UTC, sqbell approved these changes

2018-04-16 08:10 UTC, jonkerz commented on lib/fortytwoish/client.rb
> +    end
> commit sha sounds like my last name

:smile: :smile: :smile:

2018-04-16 14:28 UTC, merged